
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  password: 'password',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  image: 'image',
  imageUrl: 'imageUrl',
  surname: 'surname',
  biography: 'biography'
};

exports.Prisma.RoleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PermissionScalarFieldEnum = {
  id: 'id',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FontAuthorScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  name: 'name',
  type: 'type',
  email: 'email',
  supportEmail: 'supportEmail',
  avatarUrl: 'avatarUrl',
  bannerUrl: 'bannerUrl',
  bio: 'bio',
  website: 'website',
  dafontProfileUrl: 'dafontProfileUrl',
  profileInfoUrl: 'profileInfoUrl',
  donation: 'donation',
  nationality: 'nationality',
  languagesSpoken: 'languagesSpoken',
  isVerified: 'isVerified',
  socialLinks: 'socialLinks',
  metrics: 'metrics',
  businessInfo: 'businessInfo',
  specialties: 'specialties',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SeoModuleScalarFieldEnum = {
  id: 'id',
  metaTitle: 'metaTitle',
  metaDescription: 'metaDescription',
  keywords: 'keywords',
  ogTitle: 'ogTitle',
  ogDescription: 'ogDescription',
  ogImageUrl: 'ogImageUrl',
  ogImageAlt: 'ogImageAlt',
  twitterCard: 'twitterCard',
  twitterTitle: 'twitterTitle',
  twitterDescription: 'twitterDescription',
  twitterImageUrl: 'twitterImageUrl',
  twitterImageAlt: 'twitterImageAlt',
  canonicalUrl: 'canonicalUrl',
  noIndex: 'noIndex',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FontVariantScalarFieldEnum = {
  id: 'id',
  fontFamilyName: 'fontFamilyName',
  weight: 'weight',
  style: 'style',
  woff2Url: 'woff2Url',
  label: 'label',
  ingredientId: 'ingredientId'
};

exports.Prisma.IngredientScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  category: 'category',
  creator: 'creator',
  rating: 'rating',
  symbol: 'symbol',
  formula: 'formula',
  importedFrom: 'importedFrom',
  licenseType: 'licenseType',
  isVariable: 'isVariable',
  userRating: 'userRating',
  userRatingsCount: 'userRatingsCount',
  authorId: 'authorId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FormulaScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  slug: 'slug',
  fontCategory: 'fontCategory',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PrescriptionScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  description: 'description',
  imageUrl: 'imageUrl',
  insight: 'insight',
  published: 'published',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  primaryFontId: 'primaryFontId',
  secondaryFontId: 'secondaryFontId',
  seoId: 'seoId'
};

exports.Prisma.AdminSettingsScalarFieldEnum = {
  id: 'id',
  siteLanguage: 'siteLanguage',
  siteTimezone: 'siteTimezone',
  maintenanceActive: 'maintenanceActive',
  maintenanceMessage: 'maintenanceMessage',
  letterTFontFamily: 'letterTFontFamily',
  letterTFontSizePercent: 'letterTFontSizePercent',
  logoLightModeColor: 'logoLightModeColor',
  logoDarkModeColor: 'logoDarkModeColor',
  heroWordmarkFonts: 'heroWordmarkFonts',
  heroWordmarkLoop: 'heroWordmarkLoop',
  heroWordmarkLoopSpeed: 'heroWordmarkLoopSpeed',
  marqueeActive: 'marqueeActive',
  marqueeText: 'marqueeText',
  marqueeType: 'marqueeType',
  marqueeTextColor: 'marqueeTextColor',
  marqueeBgColor: 'marqueeBgColor',
  popupActive: 'popupActive',
  popupImageUrl: 'popupImageUrl',
  popupHeadline: 'popupHeadline',
  popupMessage: 'popupMessage',
  popupCtaLabel: 'popupCtaLabel',
  popupCtaLink: 'popupCtaLink',
  popupFrequency: 'popupFrequency',
  popupFrequencyDays: 'popupFrequencyDays',
  emailProvider: 'emailProvider',
  gmailClientId: 'gmailClientId',
  gmailClientSecret: 'gmailClientSecret',
  gmailSenderName: 'gmailSenderName',
  gmailConnected: 'gmailConnected',
  gmailConnectedEmail: 'gmailConnectedEmail',
  gmailRefreshToken: 'gmailRefreshToken',
  smtpHost: 'smtpHost',
  smtpPort: 'smtpPort',
  smtpUser: 'smtpUser',
  smtpPassword: 'smtpPassword',
  smtpSecure: 'smtpSecure',
  smtpFromEmail: 'smtpFromEmail',
  smtpFromName: 'smtpFromName',
  smtpAuthType: 'smtpAuthType',
  smtpOauthClientId: 'smtpOauthClientId',
  smtpOauthClientSecret: 'smtpOauthClientSecret',
  smtpOauthRefreshToken: 'smtpOauthRefreshToken',
  smtpOauthAccessUrl: 'smtpOauthAccessUrl',
  resendApiKey: 'resendApiKey',
  resendFromEmail: 'resendFromEmail',
  resendFromName: 'resendFromName',
  credentialsVault: 'credentialsVault',
  integrationsConfig: 'integrationsConfig',
  notificationChannels: 'notificationChannels',
  slackWebhookUrl: 'slackWebhookUrl',
  require2fa: 'require2fa',
  sessionTimeoutMinutes: 'sessionTimeoutMinutes',
  ipAllowlist: 'ipAllowlist',
  auditRetentionDays: 'auditRetentionDays',
  cookieBannerActive: 'cookieBannerActive',
  cookieBannerText: 'cookieBannerText',
  privacyPolicyUrl: 'privacyPolicyUrl',
  termsOfServiceUrl: 'termsOfServiceUrl',
  gdprRequestEmail: 'gdprRequestEmail',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TagScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PostScalarFieldEnum = {
  id: 'id',
  postType: 'postType',
  title: 'title',
  slug: 'slug',
  caption: 'caption',
  description: 'description',
  thumbnailUrl: 'thumbnailUrl',
  imageUrl: 'imageUrl',
  imageAlt: 'imageAlt',
  insight: 'insight',
  published: 'published',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  authorId: 'authorId',
  seoId: 'seoId'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  User: 'User',
  Role: 'Role',
  Permission: 'Permission',
  FontAuthor: 'FontAuthor',
  SeoModule: 'SeoModule',
  FontVariant: 'FontVariant',
  Ingredient: 'Ingredient',
  Formula: 'Formula',
  Prescription: 'Prescription',
  AdminSettings: 'AdminSettings',
  Tag: 'Tag',
  Post: 'Post'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
